-- CREATE THE DATABASE AND SWITCH TO IT
CREATE DATABASE IF NOT EXISTS noteshare;
USE noteshare;

-- CREATE THE USER FOR ACCESSING DATABASE
CREATE USER IF NOT EXISTS 'noteshare'@'localhost' IDENTIFIED WITH mysql_native_password BY '6387' ;

-- GRANT THE PRIVILEGES TO THE USER
GRANT ALL PRIVILEGES ON noteshare.* TO 'noteshare'@'localhost';

-- APPLY THE CHANGES
FLUSH PRIVILEGES;
