# Generated by Django 5.0.6 on 2024-06-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_file_note_is_public'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
